# Copyright 2022 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: locust-standalone
  name: locust-standalone
spec:
  replicas: ${POD_NUM}
  selector:
    matchLabels:
      app: locust-standalone
  template:
    metadata:
      labels:
        app: locust-standalone
    spec:
      containers:
        - env:
            - name: LOCUST_LOCUSTFILE
              value: /user/src/app/locustfile.py
            - name: LOCUST_HOST
              value: ${TARGET}
            - name: LOCUST_USERS
              value: "${USERS}"
            - name: LOCUST_RUN_TIME
              value: ${RUN_TIME}
            - name: LOCUST_LOGLEVEL
              value: DEBUG
            - name: REDIS_HOST
              value: ${REDIS_HOST}
          image: ${IMAGE_URL}:${IMAGE_TAG}
          resources:
            limits:
              cpu: "1"
            requests:
              cpu: "0.5"
          command: ["locust"]
          args:
            - --headless
            - --timescale
            - --grafana-url=http://${INSTANCE_IP}:3000
            - --pghost=${INSTANCE_IP}
            - --pgpassword=${PG_PASSWORD}
            - --pguser=postgres
          imagePullPolicy: IfNotPresent
          name: locust-standalone
