# Copyright 2022 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This is a basic workflow to help you get started with Actions
name: spanner-stress-demo-auto-test

# Controls when the workflow will run
on:
  push:
    branches:
      - main
  pull_request:
    types: [synchronize, opened]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: [ubuntu-latest]
    # Steps represent a sequence of tasks that will be executed as part of the job
    timeout-minutes: 30
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Pull repo
        uses: actions/checkout@v3

      - name: Lint check for yaml files
        run: |
          apt-get install yamllint -y
          yamllint -d "{extends: relaxed, rules: {line-length: {max: 200}}}" -f standard ./

      - name: Lint check for terraform files
        uses: actionshub/terraform-lint@main

      - name: Install terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.2.9

      - name: Validate terraform files
        run: cp .env_sample .env && make terraform.init

      - name: Install python 3.9
        uses: gabrielfalcao/pyenv-action@v11
        with:
          default: 3.9
          command: |
            pip install -U pip
            pip install pipenv

      - name: Lint check for python files
        run: |
          pip install flake8
          flake8 . --ignore=E501 --extend-exclude=terraform

      - name: Install dev package in local
        run: cd apps && pipenv install --dev

      - name: Install google-cloud-cli
        run: |
          bash <(curl https://sdk.cloud.google.com) --disable-prompts --install-dir=/usr/local/bin
          echo "/usr/local/bin/google-cloud-sdk/bin" >> $GITHUB_PATH

      - name: Create config for unit-test
        run: make create.emulator.config

      - name: Set emulator config
        run: make set.emulator.config

      - name: Run spanner emulator container
        run: docker-compose up -d spanner

      - name: Create database in spanner emulator
        run: |
          sleep 3
          make create.emulator.database

      - name: Run unit-test
        run: cd apps && ENV=local SPANNER_EMULATOR_HOST=localhost:9010 GOOGLE_CLOUD_PROJECT=test-local pipenv run test

      - name: Run app container
        run: |
          docker-compose down
          make run.local-app

      - name: Install library for script of loading master data
        run: pip install -r apps/scripts/requirements.txt

      - name: Run integration-test to load master data
        run: python ./apps/scripts/main.py -l 10

      - name: Run integration-test of simple stress test in local
        run: make run.local-locust

      - name: Stop containers
        if: always()
        run: docker-compose down
